// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkjuogvqscismqvknnqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJranVvZ3Zxc2Npc21xdmtubnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDU1OTIsImV4cCI6MjA2ODI4MTU5Mn0.Vi9qfZ0wK0ow51Lhdmu4SHguRZ5XumUMGFijxVURNAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});